pool:
  vmImage: 'Ubuntu 16.04'

variables:
  imageName: 'pythonsample:'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: 3.5
    architecture: 'x64'

- script: |
    docker build -f Dockerfile -t / .
    docker login -u  -p 
    docker push /
  env:
    pswd: jmdjsj903291A
    dockerId: aontimer
    imageName: pipelines-python-django:1
  displayName: 'Build and push Docker image'

